import { Template } from './types';

export const mockTemplates: Template[] = [
  {
    id: '1',
    name: 'Computer Repair Receipt',
    slug: 'computer-repair-receipt',
    sections: [
      {
        type: 'header',
        id: 'header-1',
        alignment: 'center',
        logoSize: 50,
        businessDetails: 'Quantum PC Repair\n3420 Innovation Drive\nAustin, TX 78758',
        dividerAtBottom: true,
        dividerStyle: 'dashed',
      },
      {
        type: 'custom_message',
        id: 'message-1',
        alignment: 'left',
        message: 'Computer Repair Receipt\nReceipt #: QRP-2047',
        dividerAtBottom: true,
        dividerStyle: 'dashed',
      },
      {
        type: 'items_list',
        id: 'items-1',
        items: [
          { quantity: 1, item: 'Laptop Virus Removal', price: 120.00 },
          { quantity: 1, item: 'SSD Upgrade (500GB)', price: 150.00 },
          { quantity: 1, item: 'System Tune-up & Diagnostics', price: 75.00 },
        ],
        totalLines: [
          { title: 'Subtotal', value: 345.00 },
          { title: 'Tax (8.25%)', value: 28.46 },
        ],
        tax: {
          title: 'Tax',
          value: 8.25,
        },
        total: {
          title: 'Total',
          price: 373.46,
        },
        dividerAtBottom: true,
        dividerStyle: 'dashed',
      },
      {
        type: 'payment',
        id: 'payment-1',
        paymentType: 'card',
        cashFields: [
          { title: 'Cash Tendered', value: '$400.00' },
          { title: 'Change', value: '$26.54' },
        ],
        cardFields: [
          { title: 'Card number', value: '**** **** **** 4922' },
          { title: 'Card type', value: 'Debit' },
          { title: 'Card entry', value: 'Chip' },
          { title: 'Date/time', value: '11/20/2019 11:09 AM' },
          { title: 'Reference #', value: '62845289260246240685C' },
          { title: 'Status', value: 'APPROVED' },
        ],
        dividerAtBottom: true,
        dividerStyle: 'dashed',
      },
      {
        type: 'date_time',
        id: 'datetime-1',
        alignment: 'left',
        date: '5/24/2025, 8:02:48 AM',
        dividerAtBottom: false,
        dividerStyle: 'dashed',
      },
      {
        type: 'barcode',
        id: 'barcode-1',
        size: 2,
        length: 13,
        value: '1234567890128',
        dividerAtBottom: false,
        dividerStyle: 'dashed',
      },
    ],
    settings: {
      currency: '$',
      currencyFormat: 'symbol_before',
      font: 'mono',
      textColor: '#000000',
      showBackground: false,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Restaurant Receipt',
    slug: 'restaurant-receipt',
    sections: [
      {
        type: 'header',
        id: 'header-2',
        alignment: 'center',
        logoSize: 60,
        businessDetails: 'The Golden Fork\n456 Culinary Ave\nNew York, NY 10001',
        dividerAtBottom: true,
        dividerStyle: 'solid',
      },
      {
        type: 'date_time',
        id: 'datetime-2',
        alignment: 'center',
        date: new Date().toLocaleString(),
        dividerAtBottom: true,
        dividerStyle: 'solid',
      },
      {
        type: 'items_list',
        id: 'items-2',
        items: [
          { quantity: 2, item: 'Caesar Salad', price: 24.00 },
          { quantity: 1, item: 'Grilled Salmon', price: 32.00 },
          { quantity: 2, item: 'House Wine', price: 18.00 },
        ],
        totalLines: [
          { title: 'Subtotal', value: 74.00 },
          { title: 'Tax (8.875%)', value: 6.57 },
        ],
        tax: {
          title: 'Tax',
          value: 8.875,
        },
        total: {
          title: 'Total',
          price: 80.57,
        },
        dividerAtBottom: true,
        dividerStyle: 'solid',
      },
      {
        type: 'payment',
        id: 'payment-2',
        paymentType: 'cash',
        cashFields: [
          { title: 'Cash Tendered', value: '$100.00' },
          { title: 'Change', value: '$19.43' },
        ],
        cardFields: [
          { title: 'Card number', value: '**** **** **** 1234' },
          { title: 'Card type', value: 'Credit' },
          { title: 'Card entry', value: 'Chip' },
          { title: 'Date/time', value: new Date().toLocaleString() },
          { title: 'Reference #', value: 'REF123456789' },
          { title: 'Status', value: 'APPROVED' },
        ],
        dividerAtBottom: false,
        dividerStyle: 'dashed',
      },
    ],
    settings: {
      currency: '$',
      currencyFormat: 'symbol_before',
      font: 'mono',
      textColor: '#000000',
      showBackground: false,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Gas Station Receipt',
    slug: 'gas-station-receipt',
    sections: [
      {
        type: 'header',
        id: 'header-3',
        alignment: 'center',
        logoSize: 55,
        businessDetails: 'QuickFuel Station\n789 Highway Blvd\nHouston, TX 77002',
        dividerAtBottom: true,
        dividerStyle: 'dotted',
      },
      {
        type: 'date_time',
        id: 'datetime-3',
        alignment: 'left',
        date: new Date().toLocaleString(),
        dividerAtBottom: true,
        dividerStyle: 'dotted',
      },
      {
        type: 'items_list',
        id: 'items-3',
        items: [
          { quantity: 12.5, item: 'Regular Unleaded (gal)', price: 43.75 },
        ],
        totalLines: [],
        tax: {
          title: 'Tax',
          value: 0,
        },
        total: {
          title: 'Total',
          price: 43.75,
        },
        dividerAtBottom: true,
        dividerStyle: 'dotted',
      },
      {
        type: 'payment',
        id: 'payment-3',
        paymentType: 'card',
        cashFields: [
          { title: 'Cash Tendered', value: '$50.00' },
          { title: 'Change', value: '$6.25' },
        ],
        cardFields: [
          { title: 'Card number', value: '**** **** **** 1234' },
          { title: 'Card type', value: 'Credit' },
          { title: 'Card entry', value: 'Contactless' },
          { title: 'Date/time', value: new Date().toLocaleString() },
          { title: 'Reference #', value: 'REF' + Math.random().toString(36).substr(2, 9).toUpperCase() },
          { title: 'Status', value: 'APPROVED' },
        ],
        dividerAtBottom: false,
        dividerStyle: 'dashed',
      },
      {
        type: 'barcode',
        id: 'barcode-3',
        size: 1.5,
        length: 13,
        value: '9876543210987',
        dividerAtBottom: false,
        dividerStyle: 'dashed',
      },
    ],
    settings: {
      currency: '$',
      currencyFormat: 'symbol_before',
      font: 'mono',
      textColor: '#000000',
      showBackground: false,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
